import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/context/GlobalProvider";
import ProductSheet from "@/components/ProductSheet/ProductSheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <GlobalProvider>
          <main className="flex flex-col flex-1 h-full w-full relative">
            <div className="w-full max-w-6xl m-auto px-4">
              {children}
            </div>
            <ProductSheet />
          </main>
        </GlobalProvider>
      </body>
    </html>
  );
}
